export const peaks = [
  { name: 'Mount Rainier', state: 'Washington', country: 'USA', elevation: 14411, difficulty: 'Hard', region: 'Pacific Northwest', season: 'Jun – Sep', routes: ['Disappointment Cleaver', 'Liberty Ridge', 'Emmons Glacier'], popularity: [5, 3, 8, 15, 35, 90, 100, 95, 60, 20, 8, 4] },
  { name: 'Denali', state: 'Alaska', country: 'USA', elevation: 20310, difficulty: 'Very Hard', region: 'Alaska', season: 'Apr – Jul', routes: ['West Buttress', 'Cassin Ridge', 'West Rib'], popularity: [5, 10, 40, 80, 100, 90, 60, 20, 5, 2, 1, 1] },
  { name: 'Mount Whitney', state: 'California', country: 'USA', elevation: 14505, difficulty: 'Moderate', region: 'Sierra Nevada', season: 'Jul – Sep', routes: ['Main Trail', "Mountaineer's Route", 'East Face'], popularity: [2, 2, 5, 10, 30, 70, 100, 95, 60, 15, 3, 1] },
  { name: 'Longs Peak', state: 'Colorado', country: 'USA', elevation: 14259, difficulty: 'Hard', region: 'Rockies', season: 'Jul – Sep', routes: ['Keyhole Route', 'Loft Route', 'Diamond Face'], popularity: [2, 2, 4, 8, 25, 65, 100, 90, 50, 12, 3, 1] },
  { name: 'Mount Shasta', state: 'California', country: 'USA', elevation: 14179, difficulty: 'Hard', region: 'Cascades', season: 'Apr – Jun', routes: ['Avalanche Gulch', 'Casaval Ridge', 'Hotlum Glacier'], popularity: [5, 8, 20, 60, 100, 90, 50, 30, 15, 8, 4, 3] },
  { name: 'Mount Baker', state: 'Washington', country: 'USA', elevation: 10781, difficulty: 'Moderate', region: 'Pacific Northwest', season: 'May – Sep', routes: ['Coleman-Deming', 'Easton Glacier', 'Thunder Glacier'], popularity: [2, 2, 5, 15, 50, 85, 100, 90, 55, 15, 3, 1] },
  { name: 'Aconcagua', state: 'Mendoza', country: 'Argentina', elevation: 22838, difficulty: 'Very Hard', region: 'South America', season: 'Nov – Feb', routes: ['Normal Route', 'Polish Glacier', 'South Face'], popularity: [80, 100, 60, 10, 3, 1, 1, 1, 5, 15, 50, 75] },
  { name: 'Cotopaxi', state: 'Cotopaxi Province', country: 'Ecuador', elevation: 19347, difficulty: 'Hard', region: 'South America', season: 'Nov – Apr', routes: ['Normal Route', 'North Face'], popularity: [70, 60, 50, 30, 15, 5, 5, 10, 20, 40, 65, 80] },
  { name: 'Huascaran', state: 'Ancash', country: 'Peru', elevation: 22205, difficulty: 'Very Hard', region: 'South America', season: 'May – Sep', routes: ['Southwest Face', 'North Summit'], popularity: [2, 2, 4, 10, 70, 100, 90, 80, 40, 8, 2, 1] },
  { name: 'Illimani', state: 'La Paz', country: 'Bolivia', elevation: 21122, difficulty: 'Very Hard', region: 'South America', season: 'May – Sep', routes: ['Normal Route', 'South Ridge'], popularity: [2, 2, 4, 10, 65, 95, 100, 85, 45, 8, 2, 1] },
]